Test: kill background jobs even on failure

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -1,11 +1,20 @@
 #!/usr/bin/env bash
 set -e
 
+trap 'cleanup; echo >&2 "FAILED!"' 0
+cleanup() { progress "Cleaning up"; kill $(jobs -p) >/dev/null ; }
+clean_exit() {
+    cleanup
+    trap '' 0
+    error_code=$(shift)
+    echo >&2 "$@"
+    exit $error_code
+}
+
 type pytest > /dev/null \
-    || { echo 'Please install pytest for python2 via pip.'
-         echo 'On ubuntu xenial run:: `pip2 install pip && pip2 install --user pytest`'
-         exit 1
-       }
+    || clean_exit 1 -n \
+            'Please install pytest for python2 via pip.\n' \
+            'On ubuntu xenial run:: `pip2 install pip && pip2 install --user pytest`'
 
 progress() { echo ==== "$@" ; }
 
@@ -40,4 +49,4 @@ sleep 1
 progress "Running tests"
 pytest ./src/RVMaster/test-monitors.py
 
-kill $(jobs -p)
+clean_exit 0
